const SKILL_ICON_URLS = {
  
  "Appel astral": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_ORB_Active_OrbSummon.webp",
  "Barrage de boules de feu": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_ST_FireCombo.webp",
  "Barrière": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_ORB_DefenseActionSkill.webp",
  "Barrière de riposte": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_SH_BuffAttack_AA.webp",
  "Bombardement concentré": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_ST_WideAreaAttack_SP.webp",
  "Bombe dimensionnelle": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_ORB_BasicAttack.webp",
  "Bouclier mystique": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_ST_defenceAction_AA.webp",
  "Bouclier chaotique": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_WA_DefenceAction.webp",
  "Boule de mana": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_ST_BasicAttack.webp",
  "Brume karmique": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_WA_GR_CurseSpread.webp",
  "Cercle magique corrompu": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_WA_CurseArea_AA.webp",
  "Combat acharné": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_SW2_MainAttack_AA.webp",
  "Copier le satellite": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_ORB_Active_Satellite.webp",
  "Coup corrupteur": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/WeaponSpecialization/M_WP_WA_RARE_SUB.webp",
  "Coup de bouclier": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_SW_SH_S_DebuffAttack_AA.webp",
  "Coup étourdissant": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_KN_SR_ShockStun_AA.webp",
  "Crochet à chaîne": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_SW_MoveSkill_AA.webp",
  "Déluge infernal": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_ST_S_Meteor_SP.webp",
  "Effleurement du désespoir": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_WA_Corruption_AA.webp",
  "Effondrement de supernova": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_ORB_Active_GravityCollapse.webp",
  "Encoche de zéphyr": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_BO_StrongShot_AA.webp",
  "Entaille": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_SW_BasicAttack.webp",
  "Entaille du néant": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_ORB_Active_OrbitSlash.webp",
  "Faille": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_ORB_Passive_ExpandRift.webp",
  "Faim de Tevent enragé": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_SI_Weapon_92.webp",
  "Fleur filante": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/WeaponSpecialization/M_ALL_SKILL_4.webp",
  "Flèche piégeante": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_BO_BindShot_AA.webp",
  "Frappe de représailles": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_SP_ComboBuff.webp",
  "Invocation de satellite": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_ORB_Active_Satellite.webp",
  "Lance de la destruction": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/WeaponSpecialization/M_ALL_SKILL_12.webp",
  "Lancer de bouclier": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_SW_SH_S_ShieldThrow.webp",
  "Malédiction explosive": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_WA_GR_CurseBurst_AA.webp",
  "Marque de détonation": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_CR_ArmorBreakShot_SP.webp",
  "Moisson d'âmes du faucheur d'argent": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Icon/Item_128/Misc/Perk_crossbow_aa_t3_normal_002.webp",
  "Nuances de souffrance": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_SW_TauntBuff_Attack_AA.webp",
  "Pluie de lances de glace": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_ST_IceSpear_SP.webp",
  "Riposte sagace": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_SW_SH_S_ManaAttack.webp",
  "Ruée précise": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_KN_SR_DashAttack_AA.webp",
  "Ruée stellaire": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_ORB_Active_Laser.webp",
  "Ruée stratégique": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_SW_SH_DashAttack_AA.webp",
  "Récri de mère Nature": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_CR_AddProjectile.webp",
  "Tir de base": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_CR_BasicShot.webp",
  "Tir de point faible": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_CR_WeakPointShot.webp",
  "Toucher putréfiant": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_WA_CurseArea_SP.webp",
  "Venin corrupteur de la reine Bellandir enragée": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_SI_Weapon_89.webp",
  "Vitesse de la lumière": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/WeaponSpecialization/M_ALL_SKILL_3.webp",
  "Voie lactée": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_ORB_Active_OrbShoot_SP_1.webp",
  "Volonté brisée": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_SW2_DefenseDebuffAttack.webp",
  "Écho stellaire": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_ORB_Passive_SubProjectile.webp",
  "Éclair du jugement": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_ST_PowerAttack.webp",
  "Éclairs en chaîne": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_ST_MainAttack_AA.webp",
  "Éclatement abyssal": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/WeaponSpecialization/M_WP_WA_HERO_ATK.webp",
  "Éruption de mana": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_ST_AddProjectile_AA.webp",
  "Vague infernale": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_ST_WideAreaDebuffAttack_AA.webp",
  "Vipère mortelle": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/WeaponSpecialization/M_ALL_SKILL_1.webp",
  "Mitraillage": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_BO_MultiShot_AA.webp",
  "Ascension du dragon": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/WeaponSpecialization/M_ALL_SKILL_8.webp",
  "Pointe de flèche de Roxie": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_BO_WindBonusProjectile.webp",
  "Tir adroit": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_BO_DefenceAction_AA.webp",
  "Contresort": "https://i.postimg.cc/d73G35qB/Contresort.png",
  "^<imgf=IMG_PartyMatching_MainAttacker> Épée du jugement": "https://i.postimg.cc/VSvXvKYg/epee-du-jugement.png",
  "Pic foudroyant": "https://i.postimg.cc/xk8L860t/Pic-foudroyant.png",
  "Sphère brûlante": "https://i.postimg.cc/nsrqr3HT/Sphere-brulante.png",
  "Contrat vampirique": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_WA_GR_CurseAttackHeal_AA.webp",
  "Bombardement enflammé": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_ST_WideAreaAttack_AA.webp",
  "Destructeur d'étoile": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_ORB_Active_RollingBall.webp",
  "Explosion interstellaire": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_ORB_Active_OrbExplosion.webp",
  "Fureur brutale": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_SP_RapidThrust_SP_1.webp",
  "Lame guillotine": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_SW2_PowerAttack_SP.webp",
  "Entaille mutilante": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_SP_CrossAttack_SP.webp",
  "Fureur cyclonique": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_SP_RapidAttack.webp",
  "Colère mortelle": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_SP_LowHpAttack.webp",
  "Coup fatal": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_SW2_CounterAttack_SP.webp",
  "Arc d'abattage": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_SP_ThrustPull.webp",
  "Entaille double": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_SW2_BasicAttack.webp",
  "Blocage patient": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_SP_DefenceAction.webp",
  "Entaille double": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_SW2_BasicAttack.webp",
  "Taillade": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_SP_BasicAttack.webp",
  "Ruée déferlante": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_SP_DashAttack.webp",
  "Rayon apocalyptique": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_WA_LinkLaser_SP.webp",
  "Givre tranchant": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_SW2_GaiaCrash_SP.webp",
  "Entaille tournoyante": "https://i.postimg.cc/BXfzJcZY/Entaille-tournoyante.png",
  
  "Abyssal Burst": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/WeaponSpecialization/M_WP_WA_HERO_ATK.webp",
  "Agile Shot": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_BO_DefenceAction_AA.webp",
  "Chain Lightning": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_ST_MainAttack_AA.webp",
  "Chaotic Shield": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_WA_DefenceAction.webp",
  "Copy Satellite": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_ORB_Active_Satellite.webp",
  "Corrupting Hit": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/WeaponSpecialization/M_WP_WA_RARE_SUB.webp",
  "Curse Explosion": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_WA_GR_CurseBurst_AA.webp",
  "Decaying Touch": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_WA_CurseArea_SP.webp",
  "Destruction Spear": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/WeaponSpecialization/M_ALL_SKILL_12.webp",
  "Detonation Mark": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_CR_ArmorBreakShot_SP.webp",
  "Dimensional Bomb": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_ORB_BasicAttack.webp",
  "Enraged Tevent's Hunger": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_SI_Weapon_92.webp",
  "Ensnaring Arrow": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_BO_BindShot_AA.webp",
  "Falling Flower": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/WeaponSpecialization/M_ALL_SKILL_4.webp",
  "Fireball Barrage": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_ST_FireCombo.webp",
  "Focused Fire Bombs": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_ST_WideAreaAttack_SP.webp",
  "Hellfire Rain": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_ST_S_Meteor_SP.webp",
  "Inferno Wave": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_ST_WideAreaDebuffAttack_AA.webp",
  "Judgment Lightning": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_ST_PowerAttack.webp",
  "Manaball": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_ST_BasicAttack.webp",
  "Manaball Eruption": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_ST_AddProjectile_AA.webp",
  "Milky Way": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_ORB_Active_OrbShoot_SP_1.webp",
  "Mother Nature's Protest": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_CR_AddProjectile.webp",
  "Rift Fracture": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_ORB_Passive_ExpandRift.webp",
  "Silver Reaper's Soul Harvest": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Icon/Item_128/Misc/Perk_crossbow_aa_t3_normal_002.webp",
  "Starcalling": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_ORB_Active_OrbSummon.webp",
  "Stellar Dash": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_ORB_Active_Laser.webp",
  "Stellar Echo": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_ORB_Passive_SubProjectile.webp",
  "Strafing": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_BO_MultiShot_AA.webp",
  "Touch of Despair": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_WA_Corruption_AA.webp",
  "Void Slash": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_ORB_Active_OrbitSlash.webp",
  "Zephyr's Nock": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_BO_StrongShot_AA.webp",
  "Summon Satellite": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_ORB_Active_Satellite.webp",
  "Weak Point Shot": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_CR_WeakPointShot.webp",
  "Counterattack Spell": "https://i.postimg.cc/d73G35qB/Contresort.png",
  "Deadly Viper": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/WeaponSpecialization/M_ALL_SKILL_1.webp",
  "Barrier": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_ORB_DefenseActionSkill.webp",
  "Vampiric Contract": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_WA_GR_CurseAttackHeal_AA.webp",
  "Serial Fire Bombs": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_ST_WideAreaAttack_AA.webp",
  "Supernova Collapse": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_ORB_Active_GravityCollapse.webp",
  "Star Destroyer": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_ORB_Active_RollingBall.webp",
  "Interstellar Explosion": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_ORB_Active_OrbExplosion.webp",
  "Lightning Speed": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/WeaponSpecialization/M_ALL_SKILL_3.webp",
  "Brutal Fury": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_SP_RapidThrust_SP_1.webp",
  "Guillotine Blade": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_SW2_PowerAttack_SP.webp",
  "Slaughtering Slash": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_SP_CrossAttack_SP.webp",
  "Cyclonic Fury": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_SP_RapidAttack.webp",
  "Mortal Wrath": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_SP_LowHpAttack.webp",
  "Death Blow": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_SW2_CounterAttack_SP.webp",
  "Culling Arc": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_SP_ThrustPull.webp",
  "Double Slash": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_SW2_BasicAttack.webp",
  "Patient Block": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_SP_DefenceAction.webp",
  "Double Slash": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_SW2_BasicAttack.webp",
  "Swing": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_SP_BasicAttack.webp",
  "Gale Rush": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_SP_DashAttack.webp",
  "Ray of Disaster": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_WA_LinkLaser_SP.webp",
  "Basic Shot": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_CR_BasicShot.webp",
  "Frost Cleaving": "https://cdn.questlog.gg/throne-and-liberty/assets/Game/Image/Skill/Active/S_WP_SW2_GaiaCrash_SP.webp",
  "Sprital Slash": "https://i.postimg.cc/BXfzJcZY/Entaille-tournoyante.png",
};

function getSkillIcon(skillName) {
  const url = SKILL_ICON_URLS[skillName];
  return url && url !== '' ? url : '';
}
